platform :ios, '8.0'
target ‘dingdingxiuSHB' do
pod 'SnapKitExtend'
pod 'Then'
pod 'Moya'
pod 'HandyJSON', '5.0.0-beta.1'
pod 'Kingfisher'
pod 'Reusable'
pod 'LLCycleScrollView'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod "UINavigation-SXFixSpace"
#import "SVProgressHUD.h"
pod 'SVProgressHUD'
pod 'SwiftyJSON'
pod 'XHToastSwift'
end
